language: java
addons:
  apt:
    packages:
      - openjdk-8-jdk
jdk:
  - openjdk8
before_install:
    - sudo apt-get -qq update
    # ant-optional is needed for ant junit
    - sudo apt-get install ant-optional